(* File assembly: turn an ordered list of per-op [Gen.generated] records into
   the three complete artifacts that lib/aten compiles and binds against:

     atg_ops.h                extern "C" declarations  (the C ABI surface)
     atg_ops.cpp              extern "C" definitions   (each calls at::<op>)
     operation_description.ml the ctypes Functions functor (one [foreign] line)

   These mirror the previously hand-written files; the per-op bodies come
   straight from [Gen], this module only supplies the surrounding boilerplate.
   Every file carries a do-not-edit banner since they are build-tree artifacts.
   Each op is preceded by a comment with its source schema signature.

   Output is assembled with the Format module: each artifact is one
   [Format.asprintf] over a fixed skeleton, with the repeated op section printed
   by [pp_print_list]. The banners and the generated fragments travel as %s/%a
   arguments (never as format-string text) so their [@generated] / [@->] stay
   literal rather than being read as Format directives. *)

let banner =
  {|/* @generated by aten_gen (bin/aten_ops_gen.ml) from native_functions.yaml.
   DO NOT EDIT. Regenerate via the dune rules in lib/aten/dune. */|}

let ml_banner =
  {|(* @generated by aten_gen (bin/aten_ops_gen.ml) from native_functions.yaml.
   DO NOT EDIT. Regenerate via the dune rules in lib/aten/dune. *)|}

(* op-section separators for [pp_print_list]: one blank line between C decls/
   defs, a paragraph break between ctypes bindings. *)
let blank_line ppf () = Format.fprintf ppf "\n"
let paragraph ppf () = Format.fprintf ppf "\n\n"

let header ops =
  let pp_decl ppf (g : Gen.generated) =
    Format.fprintf ppf "/* %s */\n%s\n" g.signature g.c_decl
  in
  Format.asprintf
    {|%s

#ifndef ATG_OPS_H_
#define ATG_OPS_H_

#include "atg_shim.h" /* atc_tensor + C scalar/handle types */

#ifdef __cplusplus
extern "C" {
#endif

%a
#ifdef __cplusplus
}
#endif

#endif /* ATG_OPS_H_ */
|}
    banner
    (Format.pp_print_list ~pp_sep:blank_line pp_decl)
    ops

let source ops =
  let pp_def ppf (g : Gen.generated) =
    Format.fprintf ppf "/* %s */\n%s\n" g.signature g.c_source
  in
  Format.asprintf
    {|%s

#include "atg_ops.h"

#include <ATen/Functions.h>

extern "C" {

%a
}  // extern "C"
|}
    banner
    (Format.pp_print_list ~pp_sep:blank_line pp_def)
    ops

let ocaml ops =
  let pp_binding ppf (g : Gen.generated) =
    Format.fprintf ppf "  (* %s *)\n  %s" g.signature g.ctypes_line
  in
  Format.asprintf
    {|%s

open Ctypes

(* The opaque tensor handle is shared with the Tensor API so a tensor from
   [C.Functions.new_] can be passed straight into these ops. *)
let atc_tensor = Function_description.atc_tensor

(* dune's ctypes requires the functor module to be named [Functions]; the
   [(instance Operations)] stanza aliases it to [C.Operations]. *)
module Functions (F : Ctypes.FOREIGN) = struct
  open F

%a
end
|}
    ml_banner
    (Format.pp_print_list ~pp_sep:paragraph pp_binding)
    ops
