(* File assembly: turn an ordered list of per-op [Gen.generated] records into
   the three complete artifacts that lib/aten compiles and binds against:

     ops.h                    extern "C" declarations  (the C ABI surface)
     ops.cpp                  extern "C" definitions   (each calls at::<op>)
     operation_description.ml the ctypes Functions functor (one [foreign] line)

   These mirror the previously hand-written files; the per-op bodies come
   straight from [Gen], this module only supplies the surrounding boilerplate.
   Every file carries a do-not-edit banner since they are build-tree artifacts.
   Each op is preceded by a comment with its source schema signature. *)

let banner =
  "/* @generated by aten_gen (bin/aten_ops_gen.ml) from native_functions.yaml.\n\
  \   DO NOT EDIT. Regenerate via the dune rules in lib/aten/dune. */"

let ml_banner =
  "(* @generated by aten_gen (bin/aten_ops_gen.ml) from native_functions.yaml.\n\
  \   DO NOT EDIT. Regenerate via the dune rules in lib/aten/dune. *)"

let header (ops : Gen.generated list) : string =
  let body =
    List.map
      (fun (g : Gen.generated) ->
        Printf.sprintf "/* %s */\n%s\n" g.signature g.c_decl)
      ops
    |> String.concat "\n"
  in
  Printf.sprintf
    "%s\n\n\
     #ifndef ATEN_CORE_OPS_H_\n\
     #define ATEN_CORE_OPS_H_\n\n\
     #include \"shim.h\" /* atc_tensor + C scalar/handle types */\n\n\
     #ifdef __cplusplus\n\
     extern \"C\" {\n\
     #endif\n\n\
     %s\n\
     #ifdef __cplusplus\n\
     }\n\
     #endif\n\n\
     #endif /* ATEN_CORE_OPS_H_ */\n"
    banner body

let source (ops : Gen.generated list) : string =
  let body =
    List.map
      (fun (g : Gen.generated) ->
        Printf.sprintf "/* %s */\n%s\n" g.signature g.c_source)
      ops
    |> String.concat "\n"
  in
  Printf.sprintf
    "%s\n\n\
     #include \"ops.h\"\n\n\
     #include <ATen/Functions.h>\n\n\
     extern \"C\" {\n\n\
     %s\n\
     }  // extern \"C\"\n"
    banner body

let ocaml (ops : Gen.generated list) : string =
  let body =
    List.map
      (fun (g : Gen.generated) ->
        Printf.sprintf "  (* %s *)\n  %s" g.signature g.ctypes_line)
      ops
    |> String.concat "\n\n"
  in
  Printf.sprintf
    "%s\n\n\
     open Ctypes\n\n\
     (* The opaque tensor handle is shared with the Tensor API so a tensor from\n\
    \   [C.Functions.new_] can be passed straight into these ops. *)\n\
     let atc_tensor = Function_description.atc_tensor\n\n\
     (* dune's ctypes requires the functor module to be named [Functions]; the\n\
    \   [(instance Operations)] stanza aliases it to [C.Operations]. *)\n\
     module Functions (F : Ctypes.FOREIGN) = struct\n\
    \  open F\n\n\
     %s\n\
     end\n"
    ml_banner body
