(* File assembly: turn an ordered list of per-op [Gen.generated] records into
   the three complete artifacts that lib/aten compiles and binds against:

     atg_ops.h                extern "C" declarations  (the C ABI surface)
     atg_ops.cpp              extern "C" definitions   (each calls at::<op>)
     operation_description.ml the ctypes Functions functor (one [foreign] line)

   These mirror the previously hand-written files; the per-op bodies come
   straight from [Gen], this module only supplies the surrounding boilerplate.
   Every file carries a do-not-edit banner since they are build-tree artifacts.
   Each op is preceded by a comment with its source schema signature. *)

let banner =
  {|/* @generated by aten_gen (bin/aten_ops_gen.ml) from native_functions.yaml.
   DO NOT EDIT. Regenerate via the dune rules in lib/aten/dune. */|}

let ml_banner =
  {|(* @generated by aten_gen (bin/aten_ops_gen.ml) from native_functions.yaml.
   DO NOT EDIT. Regenerate via the dune rules in lib/aten/dune. *)|}

let header ops =
  let body =
    List.map
      (fun (g : Gen.generated) ->
        Printf.sprintf "/* %s */\n%s\n" g.signature g.c_decl)
      ops
    |> String.concat "\n"
  in
  Printf.sprintf
    {|%s

#ifndef ATG_OPS_H_
#define ATG_OPS_H_

#include "atg_shim.h" /* atc_tensor + C scalar/handle types */

#ifdef __cplusplus
extern "C" {
#endif

%s
#ifdef __cplusplus
}
#endif

#endif /* ATG_OPS_H_ */
|}
    banner body

let source ops =
  let body =
    List.map
      (fun (g : Gen.generated) ->
        Printf.sprintf "/* %s */\n%s\n" g.signature g.c_source)
      ops
    |> String.concat "\n"
  in
  Printf.sprintf
    {|%s

#include "atg_ops.h"

#include <ATen/Functions.h>

extern "C" {

%s
}  // extern "C"
|}
    banner body

let ocaml ops =
  let body =
    List.map
      (fun (g : Gen.generated) ->
        Printf.sprintf "  (* %s *)\n  %s" g.signature g.ctypes_line)
      ops
    |> String.concat "\n\n"
  in
  Printf.sprintf
    {|%s

open Ctypes

(* The opaque tensor handle is shared with the Tensor API so a tensor from
   [C.Functions.new_] can be passed straight into these ops. *)
let atc_tensor = Function_description.atc_tensor

(* dune's ctypes requires the functor module to be named [Functions]; the
   [(instance Operations)] stanza aliases it to [C.Operations]. *)
module Functions (F : Ctypes.FOREIGN) = struct
  open F

%s
end
|}
    ml_banner body
