name: OCaml Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: devcontainer
      uses: ./.github/workflows/actions/devcontainer
      id: devcontainer
    - name: setup
      run: |
        echo 'EXEC=${{ steps.devcontainer.outputs.exec }}' >> $GITHUB_ENV
    - name: build flatc
      run: |
        ${{ env.EXEC }} make flatc
    - name: install ocaml deps
      run: |
        ${{ env.EXEC }} bash -c '. /etc/bash.bashrc && sudo OPAMROOT=$OPAMROOT make deps'
    - name: check generated schema
      run: |
        ${{ env.EXEC }} make generate-check
    - name: check formatting
      run: |
        ${{ env.EXEC }} make fmt-check
    - name: build tfview
      run: |
        ${{ env.EXEC }} make build
    - name: cache test models
      uses: actions/cache@v5
      with:
        path: models
        key: tflite-models-${{ hashFiles('models.inc', 'tools/download-model.sh') }}
    - name: download test models
      run: |
        ${{ env.EXEC }} make download-models
    - name: test all models
      run: |
        ${{ env.EXEC }} make test-models
    - name: run tfview
      run: |
        ${{ env.EXEC }} make run
    - name: test melange target
      run: |
        ${{ env.EXEC }} make test-melange
    - name: test jsoo target
      run: |
        ${{ env.EXEC }} make test-jsoo
    - name: test web-jsoo target
      run: |
        ${{ env.EXEC }} make test-web-jsoo
    - name: test web-jsoo browser
      run: |
        ${{ env.EXEC }} make test-web-jsoo-browser
