name: OCaml Images

on:
  push:
    branches:
      - '**'

jobs:
  devcontainer:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v7
      with:
        submodules: recursive
    - name: image
      uses: TheCBaH/devcontainer-action/devcontainer@v1
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
